---
development:
  dialect: postgres
  database: sysorg_development
  user: postgres
  password: riyan
  host: 127.0.0.1
  pool: 5432

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/sysorg_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/sysorg_production?sslmode=disable"}}
